/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feespaymentsystem;

import static feespaymentsystem.Payment.roomUserID;
import static feespaymentsystem.UserRegistration.randomPassword;
import javax.swing.SwingUtilities;

/**
 *
 * @author user
 */
public class ResidentInformation extends javax.swing.JFrame {

    /**
     * Creates new form ResidentInformation
     */
    public ResidentInformation() {
        initComponents();
    
        SetResidentInformation();
        
        //Gotcha button as default button.
        SwingUtilities.getRootPane(GotchaBtn).setDefaultButton(GotchaBtn);
        
    }

    private void SetResidentInformation(){
        
        IDNumberDetailsLab.setText(roomUserID);
        PasswordDetailsLab.setText(randomPassword);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResidentInformationPnl = new javax.swing.JPanel();
        MinimizeBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        GotchaBtn = new javax.swing.JButton();
        ChangePasswordLab = new javax.swing.JLabel();
        IDNumberLab = new javax.swing.JLabel();
        PasswordLab = new javax.swing.JLabel();
        PasswordDetailsLab = new javax.swing.JLabel();
        IDNumberDetailsLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ResidentInformationPnl.setBackground(new java.awt.Color(255, 255, 255));
        ResidentInformationPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MinimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        MinimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-horizontal-line-32 (2).png"))); // NOI18N
        MinimizeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MinimizeBtn.setFocusPainted(false);
        MinimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeBtnActionPerformed(evt);
            }
        });
        ResidentInformationPnl.add(MinimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 90, 40));

        ExitBtn.setBackground(new java.awt.Color(0, 0, 0));
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-delete-32 (3).png"))); // NOI18N
        ExitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ExitBtn.setFocusPainted(false);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        ResidentInformationPnl.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 90, 40));

        GotchaBtn.setBackground(new java.awt.Color(0, 0, 0));
        GotchaBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        GotchaBtn.setForeground(new java.awt.Color(255, 255, 255));
        GotchaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-thumbs-up-64.png"))); // NOI18N
        GotchaBtn.setText("Gotcha");
        GotchaBtn.setToolTipText("");
        GotchaBtn.setBorder(null);
        GotchaBtn.setFocusPainted(false);
        GotchaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GotchaBtnActionPerformed(evt);
            }
        });
        ResidentInformationPnl.add(GotchaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, -1));

        ChangePasswordLab.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        ChangePasswordLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChangePasswordLab.setText("Please change your password immediately.");
        ResidentInformationPnl.add(ChangePasswordLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        IDNumberLab.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        IDNumberLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDNumberLab.setText("ID Number:");
        ResidentInformationPnl.add(IDNumberLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        PasswordLab.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        PasswordLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLab.setText("Password:");
        ResidentInformationPnl.add(PasswordLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        PasswordDetailsLab.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        PasswordDetailsLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordDetailsLab.setToolTipText("");
        ResidentInformationPnl.add(PasswordDetailsLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        IDNumberDetailsLab.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        IDNumberDetailsLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDNumberDetailsLab.setToolTipText("");
        ResidentInformationPnl.add(IDNumberDetailsLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResidentInformationPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResidentInformationPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeBtnActionPerformed
        // TODO add your handling code here:

        this.setState(Modify.ICONIFIED);
        
    }//GEN-LAST:event_MinimizeBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:

        StaffResident staffResidentForm = new StaffResident();
        staffResidentForm.setVisible(true);
        staffResidentForm.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_ExitBtnActionPerformed

    private void GotchaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GotchaBtnActionPerformed
        // TODO add your handling code here:

        StaffResident staffResidentForm = new StaffResident();
        staffResidentForm.setVisible(true);
        staffResidentForm.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_GotchaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ResidentInformation().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangePasswordLab;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton GotchaBtn;
    private javax.swing.JLabel IDNumberDetailsLab;
    private javax.swing.JLabel IDNumberLab;
    private javax.swing.JButton MinimizeBtn;
    private javax.swing.JLabel PasswordDetailsLab;
    private javax.swing.JLabel PasswordLab;
    private javax.swing.JPanel ResidentInformationPnl;
    // End of variables declaration//GEN-END:variables
}
