/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feespaymentsystem;

/**
 *
 * @author user
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomsSidePnl = new javax.swing.JPanel();
        RoomsLogoLab = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        RoomsPnl = new javax.swing.JPanel();
        BlockABtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        MinimizeBtn = new javax.swing.JButton();
        BlockBBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomsSidePnl.setBackground(new java.awt.Color(0, 0, 0));
        RoomsSidePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomsLogoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-room-96 (1).png"))); // NOI18N
        RoomsSidePnl.add(RoomsLogoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 281, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-exit-64.png"))); // NOI18N
        jButton1.setText("Log Out");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        RoomsSidePnl.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 592, 220, 78));

        BackBtn.setBackground(new java.awt.Color(0, 0, 0));
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-left-64.png"))); // NOI18N
        BackBtn.setBorder(null);
        BackBtn.setFocusPainted(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        RoomsSidePnl.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 73));

        getContentPane().add(RoomsSidePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 670));

        RoomsPnl.setBackground(new java.awt.Color(255, 255, 255));
        RoomsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlockABtn.setBackground(new java.awt.Color(0, 0, 0));
        BlockABtn.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        BlockABtn.setForeground(new java.awt.Color(255, 255, 255));
        BlockABtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-building-filled-100 (10).png"))); // NOI18N
        BlockABtn.setText("Block A");
        BlockABtn.setToolTipText("");
        BlockABtn.setBorder(null);
        BlockABtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BlockABtn.setFocusPainted(false);
        BlockABtn.setName(""); // NOI18N
        BlockABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockABtnActionPerformed(evt);
            }
        });
        RoomsPnl.add(BlockABtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 320, 480));

        ExitBtn.setBackground(new java.awt.Color(0, 0, 0));
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-delete-32 (3).png"))); // NOI18N
        ExitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ExitBtn.setFocusPainted(false);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        RoomsPnl.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 90, 40));

        MinimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        MinimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-horizontal-line-32 (2).png"))); // NOI18N
        MinimizeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MinimizeBtn.setFocusPainted(false);
        MinimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeBtnActionPerformed(evt);
            }
        });
        RoomsPnl.add(MinimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 90, 40));

        BlockBBtn.setBackground(new java.awt.Color(0, 0, 0));
        BlockBBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        BlockBBtn.setForeground(new java.awt.Color(255, 255, 255));
        BlockBBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-building-100 (1).png"))); // NOI18N
        BlockBBtn.setText("Block B");
        BlockBBtn.setToolTipText("");
        BlockBBtn.setBorder(null);
        BlockBBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BlockBBtn.setFocusPainted(false);
        BlockBBtn.setName(""); // NOI18N
        BlockBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockBBtnActionPerformed(evt);
            }
        });
        RoomsPnl.add(BlockBBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 320, 480));

        getContentPane().add(RoomsPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 850, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Login loginform = new Login();
        loginform.setVisible(true);
        loginform.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:

        Staff staffform = new Staff();
        staffform.setVisible(true);
        staffform.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void BlockABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockABtnActionPerformed
        // TODO add your handling code here:
        
        BlockA blockaform = new BlockA();
        blockaform.setVisible(true);
        blockaform.setLocationRelativeTo(null);
        this.setVisible(false);
        

    }//GEN-LAST:event_BlockABtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void MinimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeBtnActionPerformed
        // TODO add your handling code here:

        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_MinimizeBtnActionPerformed

    private void BlockBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockBBtnActionPerformed
        // TODO add your handling code here:

        BlockB blockbform = new BlockB();
        blockbform.setVisible(true);
        blockbform.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_BlockBBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BlockABtn;
    private javax.swing.JButton BlockBBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton MinimizeBtn;
    private javax.swing.JLabel RoomsLogoLab;
    private javax.swing.JPanel RoomsPnl;
    private javax.swing.JPanel RoomsSidePnl;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
