/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feespaymentsystem;

/**
 *
 * @author user
 */
public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffSidePnl = new javax.swing.JPanel();
        StaffLogoLab = new javax.swing.JLabel();
        LogOutBtn = new javax.swing.JButton();
        StaffPnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ResidentBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        MinimizeBtn = new javax.swing.JButton();
        PaymentBtn = new javax.swing.JButton();
        RoomsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffSidePnl.setBackground(new java.awt.Color(0, 0, 0));
        StaffSidePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffLogoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-admin-settings-male-96.png"))); // NOI18N
        StaffSidePnl.add(StaffLogoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 284, -1, -1));

        LogOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        LogOutBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-exit-64.png"))); // NOI18N
        LogOutBtn.setText("Log Out");
        LogOutBtn.setBorder(null);
        LogOutBtn.setFocusPainted(false);
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        StaffSidePnl.add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 592, 220, 78));

        getContentPane().add(StaffSidePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 670));

        StaffPnl.setBackground(new java.awt.Color(255, 255, 255));
        StaffPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        StaffPnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));
        StaffPnl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, -1));
        StaffPnl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));
        StaffPnl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 360, -1, -1));

        ResidentBtn.setBackground(new java.awt.Color(0, 0, 0));
        ResidentBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        ResidentBtn.setForeground(new java.awt.Color(255, 255, 255));
        ResidentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-person-96.png"))); // NOI18N
        ResidentBtn.setText("Resident");
        ResidentBtn.setToolTipText("");
        ResidentBtn.setBorder(null);
        ResidentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ResidentBtn.setFocusPainted(false);
        ResidentBtn.setName(""); // NOI18N
        ResidentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResidentBtnActionPerformed(evt);
            }
        });
        StaffPnl.add(ResidentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, 480));

        ExitBtn.setBackground(new java.awt.Color(0, 0, 0));
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-delete-32 (3).png"))); // NOI18N
        ExitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ExitBtn.setFocusPainted(false);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        StaffPnl.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 90, 40));

        MinimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        MinimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-horizontal-line-32 (2).png"))); // NOI18N
        MinimizeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MinimizeBtn.setFocusPainted(false);
        MinimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeBtnActionPerformed(evt);
            }
        });
        StaffPnl.add(MinimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 90, 40));

        PaymentBtn.setBackground(new java.awt.Color(0, 0, 0));
        PaymentBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        PaymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        PaymentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-money-filled-96.png"))); // NOI18N
        PaymentBtn.setText("Payment");
        PaymentBtn.setToolTipText("");
        PaymentBtn.setBorder(null);
        PaymentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PaymentBtn.setFocusPainted(false);
        PaymentBtn.setName(""); // NOI18N
        PaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBtnActionPerformed(evt);
            }
        });
        StaffPnl.add(PaymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 480));

        RoomsBtn.setBackground(new java.awt.Color(0, 0, 0));
        RoomsBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        RoomsBtn.setForeground(new java.awt.Color(255, 255, 255));
        RoomsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-room-96.png"))); // NOI18N
        RoomsBtn.setText("Rooms");
        RoomsBtn.setToolTipText("");
        RoomsBtn.setBorder(null);
        RoomsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RoomsBtn.setFocusPainted(false);
        RoomsBtn.setName(""); // NOI18N
        RoomsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsBtnActionPerformed(evt);
            }
        });
        StaffPnl.add(RoomsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 250, 480));

        getContentPane().add(StaffPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 850, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResidentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResidentBtnActionPerformed
        // TODO add your handling code here:
        
        StaffResident staffresidentform = new StaffResident();
        staffresidentform.setVisible(true);
        staffresidentform.setLocationRelativeTo(null);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_ResidentBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:

        Login loginform = new Login();
        loginform.setVisible(true);
        loginform.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void MinimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeBtnActionPerformed
        // TODO add your handling code here:
        
        this.setState(Staff.ICONIFIED);

    }//GEN-LAST:event_MinimizeBtnActionPerformed

    private void PaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBtnActionPerformed
        // TODO add your handling code here:
        
        Payment paymentform = new Payment();
        paymentform.setVisible(true);
        paymentform.setLocationRelativeTo(null);
        
        this.setVisible(false);
        
        
    }//GEN-LAST:event_PaymentBtnActionPerformed

    private void RoomsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsBtnActionPerformed
        // TODO add your handling code here:
        
        Rooms roomsform = new Rooms();
        roomsform.setVisible(true);
        roomsform.setLocationRelativeTo(null);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_RoomsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Staff().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton MinimizeBtn;
    private javax.swing.JButton PaymentBtn;
    private javax.swing.JButton ResidentBtn;
    private javax.swing.JButton RoomsBtn;
    private javax.swing.JLabel StaffLogoLab;
    private javax.swing.JPanel StaffPnl;
    private javax.swing.JPanel StaffSidePnl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
