/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feespaymentsystem;

import javax.swing.SwingUtilities;

/**
 *
 * @author user
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        
        //Activate Button by default.
        SwingUtilities.getRootPane(ActivateBtn).setDefaultButton(ActivateBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomePnl = new javax.swing.JPanel();
        FeesPaymentSystemLab = new javax.swing.JLabel();
        ActivateBtn = new javax.swing.JButton();
        WelcomeLab = new javax.swing.JLabel();
        ToLab = new javax.swing.JLabel();
        MinimizeBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        WelcomeSidePnl = new javax.swing.JPanel();
        WelcomeLogoLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomePnl.setBackground(new java.awt.Color(255, 255, 255));
        WelcomePnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                WelcomePnlMouseDragged(evt);
            }
        });
        WelcomePnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WelcomePnlMousePressed(evt);
            }
        });
        WelcomePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FeesPaymentSystemLab.setFont(new java.awt.Font("Gill Sans MT", 0, 60)); // NOI18N
        FeesPaymentSystemLab.setText("FEES PAYMENT SYSTEM");
        WelcomePnl.add(FeesPaymentSystemLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        ActivateBtn.setBackground(new java.awt.Color(0, 0, 0));
        ActivateBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        ActivateBtn.setForeground(new java.awt.Color(255, 255, 255));
        ActivateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-open-door-64 (1).png"))); // NOI18N
        ActivateBtn.setText("Activate");
        ActivateBtn.setBorder(null);
        ActivateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ActivateBtn.setFocusPainted(false);
        ActivateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivateBtnActionPerformed(evt);
            }
        });
        WelcomePnl.add(ActivateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 180, -1));

        WelcomeLab.setFont(new java.awt.Font("Gill Sans MT", 0, 60)); // NOI18N
        WelcomeLab.setText("WELCOME");
        WelcomePnl.add(WelcomeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        ToLab.setFont(new java.awt.Font("Gill Sans MT", 0, 60)); // NOI18N
        ToLab.setText("TO");
        WelcomePnl.add(ToLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        MinimizeBtn.setBackground(new java.awt.Color(0, 0, 0));
        MinimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-horizontal-line-32 (2).png"))); // NOI18N
        MinimizeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MinimizeBtn.setFocusPainted(false);
        MinimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeBtnActionPerformed(evt);
            }
        });
        WelcomePnl.add(MinimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 90, 40));

        ExitBtn.setBackground(new java.awt.Color(0, 0, 0));
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-delete-32 (3).png"))); // NOI18N
        ExitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ExitBtn.setFocusPainted(false);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        WelcomePnl.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 90, 40));

        getContentPane().add(WelcomePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 850, 670));

        WelcomeSidePnl.setBackground(new java.awt.Color(0, 0, 0));
        WelcomeSidePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLogoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-so-so-96 (1).png"))); // NOI18N
        WelcomeSidePnl.add(WelcomeLogoLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 284, -1, -1));

        getContentPane().add(WelcomeSidePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActivateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivateBtnActionPerformed
        // TODO add your handling code here:

        Login loginform = new Login();
        loginform.setVisible(true);
        loginform.setLocationRelativeTo(null);

        this.setVisible(false);

    }//GEN-LAST:event_ActivateBtnActionPerformed

    private void MinimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeBtnActionPerformed
        // TODO add your handling code here:

        this.setState(Welcome.ICONIFIED);

    }//GEN-LAST:event_MinimizeBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void WelcomePnlMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomePnlMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_WelcomePnlMouseDragged

    private void WelcomePnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomePnlMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_WelcomePnlMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivateBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel FeesPaymentSystemLab;
    private javax.swing.JButton MinimizeBtn;
    private javax.swing.JLabel ToLab;
    private javax.swing.JLabel WelcomeLab;
    private javax.swing.JLabel WelcomeLogoLab;
    private javax.swing.JPanel WelcomePnl;
    private javax.swing.JPanel WelcomeSidePnl;
    // End of variables declaration//GEN-END:variables
}
